{
 "title": "UK Covid Stats",
 "time": { "from": "2020-01-01T00:00:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "UK Covid-19 Daily Stats",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Data is obtained from the UK Government Official Covid Data sources. Full dataset is polled and refreshed once a day.\n\n* Page: https://coronavirus.data.gov.uk/\n* API URL used: [click here](https://api.coronavirus.data.gov.uk/v2/data?areaType=overview&metric=cumPeopleVaccinatedCompleteByPublishDate&metric=newAdmissions&metric=newCasesBySpecimenDate&metric=newDeaths28DaysByDeathDate&metric=covidOccupiedMVBeds&format=json)\n    * Metrics: `covidOccupiedMVBeds`, `newCasesBySpecimenDate`, `cumPeopleVaccinatedCompleteByPublishDate`, `newDeaths28DaysByDeathDate`, `newAdmissions`"
   }
  },
  {
   "title": "New cases by specimen date",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"ukcoviddata-bucket\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> drop(columns: [\"areaType\", \"areaCode\", \"areaName\"])\n|> filter(fn: (r) =>\n    r._measurement == \"uk_covid_day\" and\n    r._field == \"newCasesBySpecimenDate\"\n  )\n|> sort(columns:[\"_time\"], desc: false)"
    }
   ]
  },
  {
   "title": "Patients Admitted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"ukcoviddata-bucket\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> drop(columns: [\"areaType\", \"areaCode\", \"areaName\"])\n|> filter(fn: (r) =>\n    r._measurement == \"uk_covid_day\" and\n    r._field == \"newAdmissions\"\n  )\n|> sort(columns:[\"_time\"], desc: false)"
    }
   ]
  },
  {
   "title": "Deaths when Covid Positive in last 28 days",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"ukcoviddata-bucket\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> drop(columns: [\"areaType\", \"areaCode\", \"areaName\"])\n|> filter(fn: (r) =>\n    r._measurement == \"uk_covid_day\" and\n    r._field == \"newDeaths28DaysByDeathDate\"\n  )\n|> sort(columns:[\"_time\"], desc: false)"
    }
   ]
  },
  {
   "title": "Patients on Ventilator",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"ukcoviddata-bucket\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> drop(columns: [\"areaType\", \"areaCode\", \"areaName\"])\n|> filter(fn: (r) =>\n    r._measurement == \"uk_covid_day\" and\n    r._field == \"covidOccupiedMVBeds\"\n  )\n|> sort(columns:[\"_time\"], desc: false)"
    }
   ]
  },
  {
   "title": "Cumulative Full Dosage Vaccinations",
   "type": "timeseries",
   "description": "Full population: 66,650,000",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "query": "from(bucket: \"ukcoviddata-bucket\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> drop(columns: [\"areaType\", \"areaCode\", \"areaName\"])\n|> filter(fn: (r) =>\n    r._measurement == \"uk_covid_day\" and\n    r._field == \"cumPeopleVaccinatedCompleteByPublishDate\"\n  )\n|> sort(columns:[\"_time\"], desc: false)"
    }
   ]
  },
  {
   "title": "Raw Data",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "query": "from(bucket: \"ukcoviddata-bucket\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> drop(columns: [\"areaType\", \"areaCode\", \"areaName\"])\n|> sort(columns:[\"_time\"], desc: true)"
    }
   ]
  }
 ]
}